---

- name: Ensure corosync.conf
  template: src={{ item }} dest=/etc/corosync/corosync.conf backup=no owner=root group=root mode=0644
  first_available_file:
    - "corosync.conf.{{ ansible_os_family }}.j2"
    - "corosync.conf.default.j2"
  tags:
    - corosync
    - config
  notify:
    - restart corosync

- name: Ensure corosync services
  corosync_service: name={{item.name}} ver={{item.ver}} user={{item.user}} group={{item.group}}
  with_items: services
  tags:
    - corosync
    - config

