---

- name: Ensure corosync.conf
  template: src={{ item }} dest=/etc/corosync/corosync.conf backup=no owner=root group=root mode=0644
  first_available_file:
    - "corosync.conf.{{ ansible_os_family }}.j2"
    - "corosync.conf.default.j2"
  tags:
    - corosync
    - config
  notify:
    - restart corosync

- name: Ensure pacemaker corosync service
  include: corosync_service.yml service=pacemaker
