---

- name: stop corosync services
  service: name={{ item.name }} state=stopped
  with_items: services
  when: services is defined
  tags:
   - corosync
   - service

- name: restart corosync
  service: name=corosync state=restarted
  tags:
   - corosync
   - service

- name: start corosync services
  service: name={{ item.name }} state=started
  with_items: services
  when: services is defined
  tags:
   - corosync
   - service

